### ISSUE TITLE
Hi Unity Users,

### ISSUE THREAD

**Issue by mgiaco** [ThrowTheSwitch/Unity#115]
What tools do you use for Code Coverage? 

thanks

**Comment by mvandervoord** [comment]
I believe most people are using gcov (because it's free). I've had really good success with Bullseye as well (which is not free, but is awesome).

In either case, there is obviously some setup to do, particularly with your build system.

If you're using Ceedling, there is a gcov plugin for enabling gcov support.

Mark

**Comment by mgiaco** [comment]
Hey Mark,
Thanks for your answer. I already use gcov with gcovr on Jenkins. But i need MC/DC coverage for a special project. So i will have a look at Testwell CTC++ now, bad think it isn´t open source :-(. 
Mathias

**Comment by christofferholmstedt** [comment]
@mgiaco Interesting. I've just been looking around for MC/DC testing tool but have come to the same conclusion as you, I also ended up with Testwell on the short list...but haven't tested it. Would be nice with an open source alternative.

**Comment by mgiaco** [comment]
:+1:

**Comment by mvandervoord** [comment]
When you two write one (and make it compatible with Unity), let me know. I'll be sure to post it on ThrowTheSwitch.org. ;)

**Comment by christofferholmstedt** [comment]
@mvandervoord I will put it on my todo list ;)
