### ISSUE TITLE
Memory Leak Detect?

### ISSUE THREAD

**Issue by markfink** [ThrowTheSwitch/Unity#133]
thank you for this great unit testing framework.
I am currently evaluating memory leak detection as part of unit testing. You stated in 2011 that unity does not support this:
http://throwtheswitch.squarespace.com/white-papers/comparing-unit-test-frameworks.html

I just wanted to double check if this is still the case or if there is some workaround.

**Comment by mvandervoord** [comment]
Hi Mark

Unity currently supports memory leak detection by abstracting malloc, etc. You can find this in the extras directory. 

As I sidenote: It's not a feature we spend a lot of time promoting because memory leak detection is rarely a good fit with unit testing. It's a common paradigm for a particular unit to produce memory while another unit consumes it. Testing of real-world memory handling can be handled much more effectively with mocking if you're insisting on doing it in Unit Testing... but I'd really recommend doing it in higher level tests as well (system testing, etc). You are going to want to know if your entire application leaks memory and checking individual unit tests isn't as likely to catch such a thing. 

I find that memory leak detection is one of the features that a lot of Unit Tests list (including this one) because it's easy to implement, but it's really not used often because it's the wrong fit.

Just an observation. ;)

Mark

**Comment by markfink** [comment]
Thanks for the insights. Just to make sure I got it all... Are you saying one should not use unity for higher level tests? Which tools are you recommending?

Is that all I have to do to activate the feature, or do I need additional asserts etc.?
```
#include "unity_fixture_malloc_overrides.h"
```

**Comment by mvandervoord** [comment]
You need to use all of the unity_fixtures extras. The actual implementation of the memory overrides is in the unity_fixture.c module, which unfortunately means you have to take it all. If I remember correctly, there is also a bit of a challenge making sure that unity_fixture_malloc_overrides.h gets included even from the src module to override the malloc calls.

The memory tools should be split out from the fixture extension, since they aren't REALLY dependent on each other... just stuck in the same C module at this point. 

Anyway, I use Unity for all the unit and interaction testing I do. For system testing I usually end up spinning my own framework using Ruby and Arduino for hardware interaction. The memory leak detection stuff, when dynamic memory is required, is a tricky one to fit in. I usually try to bake it into my release code itself, then check it during system tests. This might be more overhead than your application can support, which would suggest that you might want to do one of two things:

- break system testing into two levels... one that runs code WITH extras like memory leak detection turned on, and another which is your actual release code

- create high-level integration tests where you are combining multiple C modules together in order to properly support memory tests (you'd need all the modules that create or consume the memory). This is back to being a good fit for Unit Testing (and therefore Unity). The challenge of integration tests (no matter what framework) is that they can start to pull in a lot of mock/stub interfaces. It's doable, but might be more challenging than you hope.

Mark
