### ISSUE TITLE
Wrong cast in UNITY_TEST_ASSERT_EQUAL_UINT64

### ISSUE THREAD

**Issue by defusix** [ThrowTheSwitch/Unity#155]
Hey hey,
The macro `UNITY_TEST_ASSERT_EQUAL_UINT64` in `unity_internals.h` is casting it's arguments to a `_U_SINT` type. It would look nicer if it was casted to a `_U_UINT`. I don't think it technically makes a different.

**Comment by mvandervoord** [comment]
When it prints are you actually seeing an error or are you just talking about the cast to get it into the UnityAssertEqualNumber function in the first place? If it's the latter, it's casting to _U_SINT because that's the argument that UnityAssertEqualNumber takes for all numbers (and then it is later recast back). If you're actually seeing a print error, then I definitely want to fix it. :)

**Comment by defusix** [comment]
It was just about the cast to get it into `UnityAssertEqualNumber`.

**Comment by mvandervoord** [comment]
:) Cool. Thanks for checking on it! I believe it's correct, though, as it gets cast back later... we just had to choose something large enough to hold everything before we passed it into the shared function. So I'm going to close this issue.
