### ISSUE TITLE
UNITY_OUTPUT_CHAR broken again when prototype doesn't match

### ISSUE THREAD

**Issue by xor-gate** [ThrowTheSwitch/Unity#200]
It is a bad situation (again) how the `UNITY_OUTPUT_CHAR` is injected into the compilation process. I will explain our use case:

We have an ARM semihosting putc implementation:
- cflags: `-DUNITY_OUTPUT_CHAR=semihosting_putc`
- `semihosting.h -  int semihosting_putc(int c)`
- `unity_internals.h - extern void UNITY_OUTPUT_CHAR(int)`

```
In file included from flash.c:7:0:
semihosting.h:63:5: error: conflicting types for 'semihosting_putc'
 int semihosting_putc(int c);
     ^
<command-line>:0:19: note: previous declaration of 'semihosting_putc' was here
Unity/src/unity_internals.h:297:13: note: in expansion of macro 'UNITY_OUTPUT_CHAR'
 extern void UNITY_OUTPUT_CHAR(int);
             ^
```

It is very unflexible by specifying the prototype again but `extern` in the internals. 
Why was it removed from the source file and moved again into the internal header?

Or do we need to wrap the putc in a matching function prototype and ignore the return value?
It is also inflexible currently because the output char function is hard-compiled into the binary (which can also be a good thing). 

Why don't we go with a approach by having a `unity_set_output_char_func` ? And get rid of all nasty defines.

**Comment by mvandervoord** [comment]
Hmmm... There is some tension between different users' needs. I'd like to find a solution which is smooth for everyone, but so far that has been elusive.

First, there is tension between those who are specifying their output_char functions in a header file and those who are specifying it via the command line. Personally, I can't stand the situation where unity declares them at all... I think they should be in a path somewhere... but this doesn't mesh well with the majority of the users who just want to assign it to putc and don't want to have to inject an extra include of stdio.h. Because this is the most common case, I've allowed the definition to enter the project to keep these people from getting warnings.

There is a second tension between those using a function like putc (which returns an unused int) and those who are using something else (which rarely returns the unneeded value). It's been argued we should make the prototype for this function be just the parts we need, which is understandable, but then it makes others handle the output somehow. This is the situation you've run into... and it's not really a reasonable position to be in either.

For awhile I had UNITY_OUTPUT_CHAR being wrapped in another macro which was basically just adding a (void) cast to the front of it to eat whatever return values might be returned. This got warnings when the function was already void (for unnecessary casts) and it didn't mesh well with the version where we declare the function (as you might imagine).

Ok, enough history. The point is that I want to fix this... it's been bothering me for awhile. I'm definitely open to hearing ideas on how that could be best accomplished. I don't *think* it involves having people write their own full wrapper functions, because this requires extra work for the most common case: where people are just using putc. 

Maybe we make the declaration a separate step? something like this when no prototype is required:

-DUNITY_OUTPUT_CHAR="(void)semihosting_putc"

And this when a prototype IS required:

-DUNITY_OUTPUT_CHAR="(void)semihosting_putc" -DUNITY_OUTPUT_CHAR_DECL="int semihosting_putc(int a)"

Does that seem clunky or decent?

**Comment by xor-gate** [comment]
I'm also fighting which will be a good approach. Hardcoding with the preprocessor has pros but having a runtime putc callback has also has pros?

**Comment by xor-gate** [comment]
I also got stuck in another project where I did use Unity. I only declared the output char and did not do anything with the flush function. How can this even work as the second statement does nothing when already is decided fflush is used... which, is of course not possible on a cortex-m3 unless self-implemented.

```
303 #ifndef UNITY_OUTPUT_FLUSH
304 /* Default to using fflush, which is defined in stdio.h */
305 #include <stdio.h>
306 #define UNITY_OUTPUT_FLUSH (void)fflush(stdout)
307 #else
308   /* If defined as something else, make sure we declare it here so it's ready for use */
309   #ifndef UNITY_OMIT_OUTPUT_FLUSH_HEADER_DECLARATION
310 extern void UNITY_OUTPUT_FLUSH(void);
311   #endif
312 #endif
313
314 #ifndef UNITY_OUTPUT_FLUSH
315 #define UNITY_FLUSH_CALL()
316 #else
317 #define UNITY_FLUSH_CALL() UNITY_OUTPUT_FLUSH
318 #endif
```

**Comment by mvandervoord** [comment]
We've cleaned up the way FLUSH works, and made OUTPUT_CHAR work the same. If you no longer want the automatic declaration, you can specify UNITY_OMIT_OUTPUT_CHAR_HEADER_DECLARATION. verbose, but effective.
