### ISSUE TITLE
Typename '_UP' conflicts with Windows header

### ISSUE THREAD

**Issue by gageas** [ThrowTheSwitch/Unity#229]
In Unity, there is typedef-ed type _UP in unity_internals.h.
MS Windows's header file (xlocinfo.h) also has macro named _UP (defined to 0x01).
As you imagine, this cause compile error.

Generally, name starts with underscore should not be used in C/C++.
I think keeping this rule is important in multi-platform software, because of portability.

**Comment by jsalling** [comment]
Noticed this one could be a small change or a sweeping change to the type names.
I read that underscore capital letter names are reserved for the implementation in C. I guess Windows headers are considered the implementation.
Currently all the Unity types start with `_U` as in `_U_UINT`. One way would be to use `U_` instead, as in `U_UINT`, `U_PTR`, or `U_ptr`. Another alternative would be lower case perhaps with a trailing `_u` since `_t` may be POSIX reserved: `u_uint`, `uint_u`, `u_f`, or `_u_uint`. 
A discussion of reserved names: http://stackoverflow.com/questions/228783/ddg#228797

@mvandervoord
What are your thoughts about changing all the type names? Would it have to be done across the other ThrowTheSwitch projects, too? Or is this too much?

**Comment by mvandervoord** [comment]
While it's mostly used in Unity internals and doesn't reach a user's code, I believe there are a few places in CMock that would have to understand the changes. Ceedling, CException, etc should all be immune to such changes.

I agree about renaming everything to avoid the opening underscore. I believe I switched to the _U at one point just to make it more readable, since there was so much under-the-hood casting going on. It's unfortunate that this was such a shortsighted decision... but sometimes even experienced programmers do dumb things. ;)

From a strictly aesthetics sense, I like the idea of the trailing _U. I'd prefer to stick with uppercase for types... just because I like it... so I'm thinking UINT_U, FLOAT_U, PTR_U, etc. How do you guys feel about that?  

If we agree, I should be able to sweep this change out pretty quick.

**Comment by gageas** [comment]
How do you think about name like TYPE_UNITY?
I'm not sure that there is no other software code have TYPE_U typename. Maybe OK, but not sure.
Longer suffix helps to decrease potential possibility of conflict.

**Comment by mvandervoord** [comment]
That's true. 

When it's a full word I tend to like it as a prefix again. I'm realizing just how many quirks I have during this conversation! ;)

How do you feel about UNITY_INT8, UNITY_PTR, UNITY_FLOAT, etc?

**Comment by jsalling** [comment]
I like the brevity of U_UINT, U_INT8, and U_PTR.
UNITY_UINT works for me, too. It's just a bit longer.

**Comment by gageas** [comment]
My post in this thread is just a suggestion and I will not complain about what Unity team's decision.

Personally, I think it is good idea to use different prefix for public and private.
User can easily choose correct macro from suggestion list of text editor, not confused by private names.

**Comment by Letme** [comment]
Well if there is a community discussion - I prefer UNITY_INT8 over U_INT8, due to more specific wording.

**Comment by 0ge** [comment]
Then I also vote for `UNITY_INT8`. :)
`U_INT8` is very ambiguous - "Unity integer 8 bits" vs "unsigned integer 8 bits". `UNITY` also specifies the purpose.

**Comment by mvandervoord** [comment]
Thanks for the feedback, everyone! I think you'll like the results.
