### ISSUE TITLE
UNITY_TEST_ASSERT_EQUAL_FLOAT (and DOUBLE) does not calculate precision correctly

### ISSUE THREAD

**Issue by mwhessel** [ThrowTheSwitch/Unity#280]
TEST_ASSERT_EQUAL_FLOAT(0.0, 1.22e-16) fails, while UNITY_FLOAT_PRECISION is 0.00001f.

My assumption is, it fails because of:
UNITY_TEST_ASSERT_FLOAT_WITHIN((UNITY_FLOAT)(expected) * (UNITY_FLOAT)UNITY_FLOAT_PRECISION, ...)
this should be:
UNITY_TEST_ASSERT_FLOAT_WITHIN((UNITY_FLOAT)UNITY_FLOAT_PRECISION, ...)

The same for double

**Comment by mvandervoord** [comment]
The documentation explains how UNITY_FLOAT_PRECISION works, though maybe not clearly enough? It's not possible to take a +/- precision range and apply it to all floating point numbers, the way you would with an integer. For example, the number 12345678.9 in single precision floating point numbers is exactly the same as the number 12345678.1, because there aren't enough bits to extend significant digits out that far. Asking it to check +/- 0.1 in that case would be impossible, let alone 0.00001. 

So instead, the precision setting represents the multiplier to the expected range that it is allowed to vary from the expected value. If your expected value was 12345678.9 and your UNITY_FLOAT_PRECISION was 0.00001, then the assertion passes if the value is within 12345678.9 * 0.00001 or +/- 123.4567.

This is a decent system most of the time, because it scales with the numbers. Larger numbers support larger names. Smaller numbers support tighter precision.

The oddity of this, as you have found, is 0. If the expected value is zero, the actual value MUST be zero. It can be any of the floating point representations of zero, but it must be a zero or it will fail.

This system honestly works really well (once you understand it) for the majority of the cases out there. When it doesn't, you can use TEST_ASSERT_FLOAT_WITHIN and give yourself more control.  :)

I hope this helps!
