### ISSUE TITLE
generate_test_runner.rb - generate one runner from multiple inputs

### ISSUE THREAD

**Issue by dueringa** [ThrowTheSwitch/Unity#293]
Is it possible to implement a feature which generates one test runner from multiple input files?
I split my tests for one module in multiple files, and don't really want to generate multiple executables.

I guess one workaround for now would be to use the auto main name generation (https://github.com/ThrowTheSwitch/Unity/blob/0547aab67ef20783c03d7eee5f0cddd8cfa4ffb4/auto/generate_test_runner.rb#L305), create one actual main, and call the test runners from there?

**Comment by mvandervoord** [comment]
I don't think this is a direction we want to go. The test file is our method of organizing our tests. Even when people are using one-test to one-unit, they tend to organize TYPES of tests into different modules.  I can see why you're asking for this, but it seems like this can be done from the build system (like ceedling) instead of being built directly into Unity.
