### ISSUE TITLE
Error message output of boolean TEST_ASSERT_xyz_MESSAGE() variants

### ISSUE THREAD

**Issue by rstahn** [ThrowTheSwitch/Unity#327]
I just noticed a subtle difference of the `TEST_ASSERT_xyz_MESSAGE()` macros for Boolean compared to other types:
- For Boolean types the user "message" argument _replaces_ the normal error message.
- For other types the user "message" argument is output _additionally_ to the error message of the assert macro without `_MESSAGE` suffix. 

### Example
- `TEST_ASSERT_EQUAL_UINT8(1,2);`
`"example.c:65 :Example_Testcase_1:FAIL: Expected 1 Was 2"`
- `TEST_ASSERT_EQUAL_UINT8_MESSAGE(1,2,"user message");`
`"example.c:95 :Example_Testcase_2:FAIL: Expected 1 Was 2. user message"`
- `TEST_ASSERT_TRUE(false);`
`"example.c:119:Example_Testcase_3:FAIL: Expected TRUE Was FALSE"`
- `TEST_ASSERT_TRUE_MESSAGE(false,"user message");`
`"example.c:157:Example_Testcase_4:FAIL: user message"`

**Question:**
Is this behavior intentional? I would have expected that Boolean asserts behave similar to the other types. This would allow to use the user message for additional information on the specific assert only. Currently I have to manually add context on the expected and actual value.

**Comment by mvandervoord** [comment]
It was intentional, yes. Originally, the booleans operated just like the others, but messages like "Expected TRUE Was FALSE" don't really say much on their own. We got a lot of complaints that this was just useless clutter in the output stream, so we eventually simplified it down to what it is now for those cases. 

If there is sufficient interest, we could always add an option to support either behavior. +1 if you want this feature. ;)

**Comment by rstahn** [comment]
Thanks for the clarification. I suspected already it was intentional but could not find any references on the issue tracker. I guess this is one of the examples where 50% of the use cases prefer the one behavior and the other 50% the other way around.

Another option might be to add additional assert variants (e.g. `_MESSAGE_ONLY()`) for all types?
