### ISSUE TITLE
*__MESSAGE asserts don't support printf formatting

### ISSUE THREAD

**Issue by rubenbe** [ThrowTheSwitch/Unity#331]
Hi!

Is there an implementation reason why printf formatting is not supported in the *__MESSAGE asserts?
After a quick glance at the code it seems to be possible to add.
My usecase is: asserts in a loop, where I can print the index when the assert fails.

Thanks!

**Comment by mvandervoord** [comment]
Yes. The majority of Unity users are aiming at embedded targets, many of which don't or won't support printf and features like that.

Loops are the classic counter example. Where you have the memory, building up an array of results and then using one of the ARRAY assertions does the trick. 

Otherwise people who have the ability use sprintf before the assertion to assemble their fail message before the iteration.

Mark

**Comment by rubenbe** [comment]
Thanks for the explanation, it's indeed a good idea to work around this limitation/feature using the _ARRAY assertions.

closing..
