### ISSUE TITLE
Add a check to see if examples compile to the CI checks

### ISSUE THREAD

**Issue by kykrueger** [ThrowTheSwitch/Unity#350]
Examples may be broken without being reported by the CI. A test should be added to see if they compile and run as expected before getting approved.

**Comment by art-of-dom** [comment]
All examples have explicit failures in them so it make it really hard to write CI against them. It's hard to both check for build success, but allow test failures as they get tangled. If you can point to a specific test that fails that is not supposed to, I can look into it. 

I will note for example 3 it did not work out of the box for me due to the yaml file's linker, but after I modified the yaml it ran as expected with both successes and failures (as intended).
