### ISSUE TITLE
Auto test generatetor scrubs string in TEST_CASE

### ISSUE THREAD

**Issue by dpostorivo** [ThrowTheSwitch/Unity#361]
I've been trying to utilize the test cases more in my unit tests, but I have run into an issue when using strings in test cases. The auto test runner seems to strip out any string.

For example, a test that looks like this:
```
TEST_CASE(0, "SUCCESS")
void test_Foo_ReturnValueMapsToString(int status, const char * str)
{
    TEST_ASSERT_STRING(foo(status), str);
}
```

Would result in the follow (which obviously wont even compile),
`
RUN_TEST(test_Foo_ReturnValueMapsToString, 0, );
`

I've tracked down the offending line which is [line 96 of the generate test runners](https://github.com/ThrowTheSwitch/Unity/blob/master/auto/generate_test_runner.rb#L96). When I comment out this line, it generates code with the string. 

I'm happy to do a PR to help fix this, but two questions:

1. What is the original intent of this line? It doesn't seem to affect any of the tests outside TEST_CASE across many test files.
2. If we still need to keep this line, is there any case outside the TEST_CASE we should keep the string in tact?

**Comment by mvandervoord** [comment]
Hi

Sorry about the delay.

The intention of this line is to avoid having the CONTENTS of a string mess with the actual parsing of a line. Instead of replacing the string with nothing as it does now, though, maybe it should be replacing the string with a sanitized version (one that removes parentheses and things like that)?
