### ISSUE TITLE
Compiling Unity with Clang's '-Weverything' and '-Werror'

### ISSUE THREAD

**Issue by shreyasbharath** [ThrowTheSwitch/Unity#41]
Clang throws a number of warnings around tests using unity_fixture.h

An example is -
 error: no previous extern declaration for non-static variable 'TEST_GROUP_GroupName' [-Werror,-Wmissing-variable-declarations]

It is because the TEST_GROUP() macro declares a global variable that is not used anywhere. I'll have a go at fixing this and submit a pull request.

**Comment by jsalling** [comment]
It looks like this and similar issues were fixed in 9e9adc0.
The Fixture compiles with `clang` `-Weverything` today. However, there will probably always be some remaining warnings in Unity. For instance, `-Wpadded` depending on the platform, a few undeclared `extern` variables, and `-Wcovered-switch-default`.
@mvandervoord Will you close?

**Comment by mvandervoord** [comment]
Thanks for checking on this. :)
