### ISSUE TITLE
Configuration options test_reset_name and test_verify_name may be broken

### ISSUE THREAD

**Issue by jvcdk** [ThrowTheSwitch/Unity#467]
Hi,

If one tries to rename `resetTest` and `verifyTest` (using the configuration options `test_reset_name` and `test_verify_name` respectively) I get a warning from gcc:
```
src/test_d_output_ramp.c:186:9: warning: implicit declaration of function 'JvcVerifyTest' [-Wimplicit-function-declaration]
```

The code compiles (I am currently not using `-Werror` for gcc) and runs, but it is still a warning.

I believe the error stems from a "static" declaration of `resetTest` and `verifyTest`. Instead it should probably be auto-generated form Ruby scripts parsing the project file (configuration options). The static declaration is here: https://github.com/ThrowTheSwitch/Unity/blob/master/src/unity.h#L52 .

I am using Ceedling, btw. And I created a related issue [Configuration options setup_name and teardown_name may be broken](https://github.com/ThrowTheSwitch/Unity/issues/466).

~Jørn

**Comment by mvandervoord** [comment]
Hi Jørn,

Unfortunately, the script that creates the test runner is only creating a c file. it doesn't create another header for you to include in your test. So when you go to compile your test, it is only looking at code you've created, plus `unity.h` and `unity_internals.h`. Neither of those files are modified during the build process.

There may be zero to many mock files used, which means if we put the definition in those, we would sometimes have an undefined error (as you have now) and sometimes have a duplicately defined error, depending on the number of mocks in that test.

I think this means that the only remaining option is for the user to solve it themselves. I see three options:

(1) The user can include a `unity_config.h` and define `UNITY_INCLUDE_CONFIG_H` to force it to automatically be loaded. This file could include the definitions so they are available to all modules during testing.

(2) The user can include the definition in a `unity_helper.h`. This might be preferable to option 1 in the situation that they are already adding their own assertions, etc... but otherwise works the same.

(3) The user can directly put the definition in the test file or in a header that they always directly include from their tests. This is a little more cumbersome in that they have to remember to include it.

Can you think of another approach? I'm definitely open to other ideas... otherwise I can include these three options as part of the documentation to make it more clear?

**Comment by jvcdk** [comment]
Hi Mark,

I think my preferred approach would be to let the Ruby scripts create a `unity_autogenerated_internals.h` which either `unity.h` or `unity_internals.h ` would include. There may, however, be issues with this approach that I don't know of (since you have not chosen/suggested that approach).

If that is not possible, I think I would choose a solution similar to your suggestion (1). It seems that it provides least amount of information for the user to remember in the future (once it is set up).

~Jørn

**Comment by mvandervoord** [comment]
Hm. This is a good thought. 

Ceedling could automatically create a `unity_config.h` which includes the new stubs. If the user has defined their own `unity_config.h`, Ceedling could just merge them and point at the new one. This way the user would never know the difference but it would all be automatic.

Thanks for the idea!

**Comment by jvcdk** [comment]
> If the user has defined their own unity_config.h, Ceedling could just merge them and point at the new one. 

I am not completely sure how this would work, but if it makes sense for you, then great :-D

**Comment by mvandervoord** [comment]
Well cool. I've fixed the Unity issue here, in that I've made it so it doesn't include the default handler when it shouldn't. I'll open an issue on Ceedling to cover this other feature to make it automatic. Thanks for the help!
