### ISSUE TITLE
Unity do not show source file name when errors

### ISSUE THREAD

**Issue by fbucafusco** [ThrowTheSwitch/Unity#474]
There is something anoying when testing heavily nested libraries with many .c files. 
For example: an error message is:
<path to c file>/some_file.c:31:<test_name>:FAIL: Expression Evaluated To FALSE
but maybe the line number 31 is not from some_file.c but from another nested function within another .c file that called TEST_ASSERT, instead. 
Tracking the file that actually failed is somehow time consuming.

**Comment by mvandervoord** [comment]
The problem isn't the framework in this case, but the way you're using it. That's not to say what you are doing is wrong, just that your expectation isn't matching the paradigm of the framework. Stick with me a moment and I think we can get this worked out.

First, Unity is primarily intended to be a Unit Testing framework. It's building an executable per unit being tested. This means that in the great majority of cases, all your tests for a particular unit (and therefore all the tests in a particular executable) are within a single Test C file. In those cases, there is never going to be an assertion buried in another test file.

The second most common case is that Unity is used for interaction testing. This includes mocking and stubbing and such. The third is that Unity is being used as in the first above, but there need to be a pool of common helpers which are used in multiple tests. In either of these cases, it's often useful to have another C module full of helper functions for testing particular things. Often, these are stand-ins for functions the unit being tested would be calling. No matter if these are hand-built helpers or automatically generated ones (like with CMock), they aren't using the same assertions that you're seeing... for exactly the reason you're seeing. (more on how they do it correctly below).

It's possible that you're one of the groups above and just don't know the tricks yet... or it's possible you're someone fairly new to unit testing in C and haven't run into some of the challenges yet. In case you're the latter (and I apologize if this isn't you. I do not intend to insult anyone... I just want to answer this completely), let's talk about group 3 -- people often come into unit testing C and expect to be able to build a single executable that will run all of their tests in a single run. It IS possible, but it's usually not desirable. The reason is because you can do a much more thorough and flexible job by testing a unit at a time. Yes, there is a bit of a time tradeoff... but the ability to fully test is worth the tradeoff.

This mini-article might help: https://www.throwtheswitch.org/build/build-unity

Okay. Circling back. If you are creating a file that contains tests or helpers or whatever that are getting called from a main test, you're going to be interested in using the `UNITY_TEST_ASSERT_` versions of the macros instead of the `TEST_ASSERT_` version. They're in `unity_internals.h` instead of `unity.h`. They accept a couple arguments more than the general assertion, taking a line number for the failure and an optional message (set to NULL if you don't want it). 

The purpose of that line number is to be able to pass the line number from the ORIGINAL line in your test that has the problem. For example, let's say I have a helper module `helpers.c` that contains this:

```
void verify_percent(int value, int line)
{
    UNITY_TEST_ASSERT_GREATER_OR_EQUAL_INT(0, value, line, "Percent Should Be At Least 0");
    UNITY_TEST_ASSERT_SMALLER_OR_EQUAL_INT(100, value, line, "Percent Should Be At Most 100");
}

#define VERIFY_PERCENT(value) verify_percent(value, __LINE__)
```

Then I could use it in my test file like so:

```
void test_GetFilter_SHOULD_AlwaysReturnAValidPercentage(void)
{
    int i;

    for (i=-5; i < 105; i++) {
        VERIFY_PERCENT( GetFilter(i) );
    }
}
```

Note that if this test fails, it is still going to report the test file, but it is now also going to report the line where VERIFY_PERCENT is CALLED in that test when it fails, so it will make the most sense to the test developer.

Okay. Let's say none of this applies to you and you still feel like you need to change the name of the FILE. It's almost always a sign that you're doing something you will regret, but you can still do it. All of Unity's internal accounting is tracked in a structure called `Unity`. You can set the filename to whatever you want by directly setting `Unity.TestFile` to point at a constant null-terminated string of your choosing.  This could be before each files' tests are begun.

I hope this helps explain things. If I've completely missed the mark, please don't hesitate to say so.

Mark

**Comment by fbucafusco** [comment]
Hi Mark, 
Wow, thanks for that huge explanation.
I think the ansewer for my original post is the UNITY_TEST_ASSERT_XXXX macros. 
I usually go beyond the unit testing and I do write many behavioral tests of complex libraries (that involve objects intantiations and so). Many times, when I have time, I randomize my tests.  Each object implementation in general has a XXX_ASSERT macro that, when running on a microcontroller, for example, has some behavior, but for testing uses the TEST_ASSERT macro. 
I think that I will use UNITY_TEST_ASSERT_XXXX macro using __LINE__ and that's it. 
Should I close the issue?
