### ISSUE TITLE
Does Unity put a limit on amount of heap memory that can be allocated?

### ISSUE THREAD

**Issue by tiwariShubhi** [ThrowTheSwitch/Unity#478]
Hi all,

I am using some malloc() calls in my tests. But I am not able to allocate more than 250 bytes using malloc().
Like a ,
`int * myPtr = (int* ) malloc(400); `
results in a segFault. malloc() does not return a NULL pointer in this case.
Other malloc() calls which request much smaller memory are working fine.
Also I free() all pointers after their use is over in each test case.

Does Unity somehow put a limit on amount of heap memory that can be allocated?
If yes, is that configurable ? 
 
Thanks,
Shubhi

**Comment by mvandervoord** [comment]
Unity itself has no effect on the way your application handles memory. If you're using the `memory` handling addon in the `extras` folder (which is automatically included with `fixtures` also), then you've chosen to override standard system calls with stubbed ones. In that case, you'll want to define `UNITY_INTERNAL_HEAP_SIZE_BYTES` to the heap size you actually need (which does indeed default to `256`)

**Comment by tiwariShubhi** [comment]
Thanks for the quick reply. 
I am not using any addons. Just unity.c, unity.h and unity_internals.h .
Does cmock have any constraints on memory ? 
Again I am using only cmock.c, cmock.h and cmock_internals.h

**Comment by mvandervoord** [comment]
I think CMock will only be an effect here if you're mocking malloc instead of using the real malloc. In that case, you're limited by CMock's internal stack size (which is also settable). 

Other common issues:

(1) If you're using a cross compiler and a simulator or remote target, it's possible you're running into the upper limits of the target itself. Tests when using CMock can take up memory quickly, particularly if you have numerous plugins enabled or the API's your mocking are large.

(2) It could be an issue with the way the memory is being handled. Test failures cause a test to end immediately, which would cause any free calls later in the test itself to get skipped. You can clean things like this up in tearDown, but you have to be careful to always init pointers back to zero and to only free when there is something to free.

(3) If you're targetting non-x86, it could be an alignment issue. You can check this by adding a test for the lower bits right after malloc is called.

If it doesn't seem any of these, is there a minimal test that you can make public that reproduces your problem?
