### ISSUE TITLE
Unity doesnt exclude Functions under #ifdef directives

### ISSUE THREAD

**Issue by Lakshmi2938** [ThrowTheSwitch/Unity#481]
I have a low level layer to be mocked , but the header file has few sections that are not enabled using #ifdef directives. 
But CMOCK create mocks for the APIs declared under those sections as well. which is creating compiler errors for me ,when i compile test application for undefined reference or unknown APIs etc.
How to avoid mocking specific APIs from a header file or particular sections under #ifdef. 

Thanks
LP

**Comment by Lakshmi2938** [comment]
example header file

#ifdef TRUE
void API_function_call1(int,int);
#endif 
#ifdef FALSE
void API_Function_Call2(int,int);
#endif 
now i want to mock areas only under TRUE . Not under FALSE section.
please let me know, how can i do it using CMOCK ?

**Comment by mvandervoord** [comment]
:)

This is the wrong forum for this. You're talking about an issue you're having with CMock, so you want the CMock issues list.

In any case, CMock has no way of knowing what defines you are using, etc. This is left to your preprocessor. Ceedling, for example, can be configured to preprocess your files before passing them to CMock, so that CMock understands which features you want included and whatnot.

**Comment by Lakshmi2938** [comment]
Thanks for the quick reply Mark VanderVoord.
Will post it in the appropriate section.
