### ISSUE TITLE
Build the result files from the makefile

### ISSUE THREAD

**Issue by janemba** [ThrowTheSwitch/Unity#515]
Hello,

I am using the following example http://www.throwtheswitch.org/build/make to build my tests with Unity framework. But I have the following error.
```
$ make test
make: *** No rule to make target 'build/results/Test_foo.txt', needed by 'test'.  Stop.
```

The results text files are generated by redirecting the *.out* executable output. I can see this from this line:
```
$(PATHR)%.txt: $(PATHB)%.$(TARGET_EXTENSION)
	-./$< > $@ 2>&1
```

But well, it doesn't seem *.out* executable are built.

**Comment by janemba** [comment]
I renamed my test files from *Test_foo.c* to *Testfoo.c.* The issue remain the same.

**Comment by janemba** [comment]
I used the same *Makefile* found in https://github.com/ThrowTheSwitch/Unity/issues/464 but the issue persist.

**Comment by mvandervoord** [comment]
Finding mistakes with `make` is an adventure. Keep in mind that it could be failing anywhere along the way... it might have figured out how to build the release, but can't find the source files, etc. Have you tried adding the `-d` flag when you call `make` in order to get debug information along the way?

Common issues that I've seen people run into:

- Capitalization mismatches (for example, a header called `foo.h` and a c file called `Foo.c`)
- Paths referenced from the wrong startpoint (calling make from a source directory when it was designed to be called form project root)

**Comment by janemba** [comment]
Nevermind. I rebuild my own Makefile  from scratch line by line. So it works now.
