### ISSUE TITLE
Unity, TEST_ASSERT_EQUAL_MEMORY fails

### ISSUE THREAD

**Issue by krish2487** [ThrowTheSwitch/Unity#552]
Hello kind folks,
I come seeking wisdom!! :-)

There is a specific issue with Unity that I have come across yesterday and despite my best efforts I am unable to fix it.
I have a header file (DriverDS.h) that contains the structure definitions for some custom datastructures I would like to use. The I have DS.c/.h and test_DS.c files which I have created using ceedling module generator. I would like to test a function DSInit.

DSInit takes two parameters  - an enum which indicates the type of datastructure to initialize  and a void pointer which has to be initialized based on the enum. 

I have a test in test_DS.c which basically creates a void pointer (pPtrUnderTest), a pointer to the custom datastructure (pExpectedValues). The test first initializes the pExpectedValues pointer to the default zero state, then passes in the pPtrUnderTest to the DSInit function.

The function itself is supposed to malloc memory for the pointer, depending on the enum, cast the pointer and set the values to null.

I check if both the pPtrUnderTest and pExpectedValues are equal after the function invocation and would expect them to be equal. 
However, this test fails. I am not sure where I am making a mistake. 
I would appreciate any help in fixing this error.

DriverDS.h
```
#ifndef DRIVER_DS
#define DRIVER_DS
#include "stdint.h"
struct POSTResults
{
	// Good is 1, Bad is 0
	bool Battery;
	bool Authentication;
	bool Transport;
};

typedef struct RuntimeSettings
{
	char TimeStamp[20];
	uint16_t POSTInterval; // Interval is specified in seconds
	struct POSTResults POST;
} Settings;

#endif // DRIVER_DS

```

DS.h

```
#ifndef DS_H
	#define DS_H
	#include "BSP.h"
	#include "DriverDS.h"

	enum Error_codes DSInit(enum DataStructures, void *pStructure);

#endif // DS_H

```

DS.c

```
#include "DS.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"
//Pass in a void pointer for the memory block
// cast the void pointer to a the appropriate structure type and malloc memory for it.
// Set each member to null
//
enum Error_codes DSInit(enum DataStructures dstype, void *pStructure)
{
	switch (dstype)
		{
		case SETTINGS:
				pStructure = malloc(sizeof(Settings));
				memset(((Settings *)pStructure)->TimeStamp, 0, sizeof(((Settings *)pStructure)->TimeStamp));
				((Settings *)pStructure)->POSTInterval = 0;
				((Settings *)pStructure)->POST.Authentication = true;
				((Settings *)pStructure)->POST.Battery = true;
				((Settings *)pStructure)->POST.Transport = true;

				break;
			case HWINFO:
				break;
			case DATASTRUCTURES_MAX:
				return ERROR;
			}
		return SUCCESS;
	}

```

test_DS.c

```

#ifdef TEST

#include "unity.h"

#include "DS.h"
#include "DriverDS.h"
#include "string.h"
#include "stdlib.h"
void setUp(void)
{
}

void tearDown(void)
{
}

void test_DS_DSInit_Settings_initializes_values_to_0(void)
{
	void *pPtrUnderTest;
	Settings *pExpectedValues = malloc(sizeof(Settings));
	memset(pExpectedValues->TimeStamp, 0, sizeof(pExpectedValues->TimeStamp));
	pExpectedValues->POSTInterval = 0;
	pExpectedValues->POST.Authentication = true;
	pExpectedValues->POST.Battery = true;
	pExpectedValues->POST.Transport = true;
	DSInit(SETTINGS, pPtrUnderTest);
	// TEST_ASSERT_EQUAL_PTR(pExpectedValues, (Settings *)pPtrUnderTest);
	TEST_ASSERT_EQUAL_MEMORY(pExpectedValues, (Settings *)pPtrUnderTest, sizeof(Settings));
}

#endif // TEST

```

Now the test fails whether I compare PTR or MEMORY. 

I see this error on the console.

```
 ceedling test:DS


Test 'test_DS.c'
----------------
Generating runner for test_DS.c...
Compiling test_DS_runner.c...
Compiling test_DS.c...
Compiling unity.c...
Compiling DS.c...
Compiling cmock.c...
Linking test_DS.out...
Running test_DS.out...

-------------------
FAILED TEST SUMMARY
-------------------
[test_DS.c]
  Test: test_DS_DSInit_Settings_initializes_values_to_0
  At line (30): "Memory Mismatch. Byte 0 Expected 0x00 Was 0x40"

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  1
PASSED:  0
FAILED:  1
IGNORED: 0

---------------------
BUILD FAILURE SUMMARY
---------------------
Unit test failures.
```

The file BSP.h contains the `enum Error_codes ` definition which for now is just ERROR or SUCCESS.

From what I see here, the pExpectedValues are being set to 0 but the function under test is not setting the memory contents to 0.  However, it is the same sequence of operation in the test module and the actual function under test.
I have literally copy pasted the code from the test file to the function and renamed it accordingly.
I m not sure what is the error I m commiting here.

I appreciate any insight and help into where I am goofing this up. 

Thanks in advance again folks!! 😄 

PS: To help troubleshoot,  I have inserted printf statements inside the function DSInit to print the values after setting them to 0. They are set correctly.

**Comment by mvandervoord** [comment]
(1) You can't compare pointers in this case because the release code being tested performs its own malloc, therefore will ALWAYS be pointing at a different memory location than your test code. So TEST_ASSERT_EQUAL_PTR is not an option.

(2) It's usually not a good idea to directly mem-compare two structs, because your compiler may be padding the structs and you have no way of controlling what is in the padded spaces (therefore you can get false failures). It's better to build an assertion for each field individually (or, if it's a struct you're going to use a lot, you can even create a custom assertion for that type which contains an assertion for each field). This is NOT the problem you have with your TEST_ASSERT_EQUAL_MEMORY, though.

(3) The problem you're running into is that you have a bug in your `DSInit` function. It's taking a pointer, when it needs to take a POINTER to a POINTER. You update the pointer by using malloc, but that update is NOT passed back out of the DSInit function, therefore any following functions never get to use it (including the test):

```
enum Error_codes DSInit(enum DataStructures dstype, void **pStructure)
{
	switch (dstype)
		{
		case SETTINGS:
				*pStructure = malloc(sizeof(Settings));
				Settings* pSettings = *pStructure;
				memset((pSettings->TimeStamp, 0, sizeof((pSettings->TimeStamp));
				pSettings->POSTInterval = 0;
				pSettings->POST.Authentication = true;
				pSettings->POST.Battery = true;
				pSettings->POST.Transport = true;

				break;
			case HWINFO:
				break;
			case DATASTRUCTURES_MAX:
				return ERROR;
			}
		return SUCCESS;
	}
```

(Bonus 1) It's a bad idea to use dynamic memory in your tests when you can avoid it. Tests are meant to be more stable than the code they're testing. There's no reason you can't create a function-scoped struct and use that (or even a const if you want).

(Bonus 2) You never free the memory that was malloc'd in `DSInit`

```
Settings *pPtrUnderTest = 0;

void setUp(void) {
    pPtrUnderTest = 0;
}

void tearDown(void) {
    if (pPtrUnderTest != 0)
        free(pPtrUnderTest);
}

void test_DS_DSInit_Settings_initializes_values_to_0(void)
{
	Settings ExpectedValues;
	ExpectedValues.TimeStamp = { 0 };
	ExpectedValues.POSTInterval = 0;
	ExpectedValues.POST.Authentication = true;
	ExpectedValues.POST.Battery = true;
	ExpectedValues.POST.Transport = true;

	DSInit(SETTINGS, pPtrUnderTest);

	TEST_ASSERT_NOT_NULL(pPtrUnderTest);
	TEST_ASSERT_EQUAL_INT8_ARRAY(ExpectedValues.TimeStamp, pPtrUnderTest->TimeStamp, 20);
	TEST_ASSERT_EQUAL_INT16(ExpectedValues.POSTInterval, pPtrUnderTest->POSTInterval);
	TEST_ASSERT_TRUE(pPtrUnderTest->POST.Authentication);
	TEST_ASSERT_TRUE(pPtrUnderTest->POST.Battery);
	TEST_ASSERT_TRUE(pPtrUnderTest->POST.Transport);
}
```

**Comment by krish2487** [comment]
@mvandervoord 
Thank you for that detailed explanation.

1. Thats what I understood and went with the memory compare.
2. Thats interesting. I assumed that the compiler being the same for the expected structure and the structure under test would behave the same in both the cases ( famous last words.. 😄 ). Essentially any padding or packing will be the same for  both the structures.. But as you suggested, I d rather not take a risk.  I ll refactor the test to test each field individually.

3. This point needs some time for me to grasp and understand.. I am almost following your explanation with a few gaps. 
If I understand you correctly, passing in a pointer and running malloc will update the pointer itself but once the DSInit function exits, the calling function still has no idea about the contents / form of pPtrUnderTest. Whereas by passing in a Pointer to Pointer, the *(pPtrUnderTest) i.e  the Value of pPtrUnderTest is the addres to a block of memory whose contents are of type Settings Struct?

Regarding the dynamic allocation, I am just experimenting for now. It is sound advice to avoid dynamic allocation. I ll certainly try and avoid it if I can. 
I have only included a part of the code, in the DeInit function, the corresponding free() call is made. :-)

Thank you very much for the help and quick response. Please give me some time to go back home and validate the suggestions. I am at work presently. I ll close the issue once I validate and do not run into further troubles. 

Thank you again @mvandervoord

**Comment by krish2487** [comment]
@mvandervoord  Thank you very much!! This pointer to pointer suggestion works! 
😄 
It does work when the address of both types, i.e a void * and a Settings* are passed in.
As I said, I havent fully grasped why this pointer to pointer indirection is required.. but I ll work a little more and try and undeerstand it. For now I am closing this issue. 

Thank you very much again!!

**Comment by mvandervoord** [comment]
Hi. Maybe I can explain it a bit more clearly?

In C, when you pass something into a function, you can change it within the function all you want, but it will be reverted back to its original contents upon exiting the function. (for example, if you pass an `int` of `3`, you could add 1 to it and use it as `4` within your function... but as soon as you exit the function, the passed value is back to `3` again. 

We work around this by using pointers. If I wanted to change that integer, I would make the function pass a `int*` instead, and then I could change it like `*val += 1;` Now it would change the actual value returned.

In your situation, you're passing a pointer to the struct. That means when we leave the function, it's kept any changes you made TO THAT STRUCT... but the pointer ITSELF has not changed... it's pointing to whatever it was pointing to originally.

This is where your problem comes in. Inside the function, you call malloc. Malloc returns a pointer to a new block of memory... therefore it's updated the POINTER, not the CONTENTS being pointed to. When we return from the function, the pointer is reverted.

We don't want the pointer to revert in your situation, therefore we need a pointer to that pointer. 

It's a bit confusing, but it's all about what you can actually change. :)

Regarding your comment on number 2 above: You are correct that the compiler will treat the Expected and the Actual structs the same way. The problem is that BOTH of those structs might have padding between fields, bytes which are not addressed by your program at all. Often, for efficiency's sake, compilers will just ignore those bytes, allowing them to be whatever values were in the memory before the struct was allocated. Therefore if I create two identical structs, the padding fields might have different values (even though all the fields I care about are identical). When we do a memory comparison, it compares ALL the memory (including the padding). We can then get false failures on the padding not matching, even though everything important matched.

**Comment by krish2487** [comment]
@mvandervoord That made infinitely more sense.. Inception-izing pointers..

To put it simply, it is the concept of passing by reference applied to pointer arguments!! 
If I pass a pointer as an argument and point it to any specific struct / memory.. then whatever changes I make to that pointer within the function are valid only within that function block.. Once the function returns.. the pointer is back to pointing to whatever it was originally.. So the only way to get around that is to pass a pointer to a pointer!! 😄 and then change the contents of the original pointer by dereferencing it once.

Did I understand that correctly??

**Comment by mvandervoord** [comment]
Yes. You have it exactly correct. :)

**Comment by krish2487** [comment]
IOW.. treat the pointer itself as a variable.. Any changes within a function block are made to the local copy of the variable.. not to the original argument itself.. In order to change the original argument.. pass it by reference.. i.e pass a pointer to the variable.. in this case.. pass a pointer to a pointer.. 
whew!! typing that out.. makes me understand better!! 😄 

Thank you again @mvandervoord .

**Comment by mvandervoord** [comment]
No problem. I'm glad I could help.

**Comment by JuPrgn** [comment]
That would be awesome if we could have a function assert to compare every fields of a struct. I was also using memory comparaison and found similar problem that the one you explained so well ! I am not sure if this could be done without much work or if this would require something to generate a function comparaison for each struct similar to mock from headers ?

**Comment by Letme** [comment]
@JuPrgn its already possible, for example to compare struct in em_dac.h you just create unity_helper.h in your test folder (depends on build system of course, but you get the idea). It would be nice to automate this on the other hand, but it seems like quite complex job considering the problems CMock has with different C styles.

em_dac.h
```
/** DAC channel init structure. */
typedef struct
{
  /** Enable channel. */
  bool               enable;

  /**
   * Peripheral reflex system trigger enable. If false, channel is triggered
   * by writing to CHnDATA.
   */
  bool               prsEnable;

  /**
   * Enable/disable automatic refresh of channel. Refresh interval must be
   * defined in common control init, please see DAC_Init().
   */
  bool               refreshEnable;

  /**
   * Peripheral reflex system trigger selection. Only applicable if @p prsEnable
   * is enabled.
   */
  DAC_PRSSEL_TypeDef prsSel;
} DAC_InitChannel_TypeDef;

```
unity_helper.c
```
void AssertEqualDAC_InitChannel_TypeDef(DAC_InitChannel_TypeDef expected, DAC_InitChannel_TypeDef actual, unsigned short line)
{
	UNITY_TEST_ASSERT_EQUAL_UINT8(expected.enable, actual.enable, line,
	                              "DAC_Init_TypeDef.enable bool failed");
	UNITY_TEST_ASSERT_EQUAL_UINT8(expected.prsEnable, actual.prsEnable, line,
	                              "DAC_Init_TypeDef.prsEnable bool failed");
	UNITY_TEST_ASSERT_EQUAL_UINT8(expected.refreshEnable, actual.refreshEnable, line,
	                              "DAC_Init_TypeDef.refreshEnable bool failed");
	UNITY_TEST_ASSERT_EQUAL_INT(expected.prsSel, actual.prsSel, line,
	                            "DAC_Init_TypeDef.prsSel enum failed");
}
```

unity_helper.h
```
#define UNITY_TEST_ASSERT_EQUAL_DAC_InitChannel_TypeDef(expected, actual, line, message)
```

**Comment by JuPrgn** [comment]
Thank you for this example ! Yes I was thinking about the automated way but you are right there are different styles and struct can be really complex sometimes.
