### ISSUE TITLE
definition of setUp/tearDown is missing in v2.5.2

### ISSUE THREAD

**Issue by TooChaos** [ThrowTheSwitch/Unity#605]
In v2.5.2 when compiling the simplest unit test file similar to the one in "Getting Start" of http://www.throwtheswitch.org/unity the linker complains cannot link to functions setUp and tearDown.

I could not find definition in unity.c. However, they are defined in v2.4.0 and I can compile it successfully too.

**Comment by mvandervoord** [comment]
Hi,

Both 'setUp' and 'tearDown' are meant to be defined in your test files. Back in 2.4.0, we had a feature which allowed both to be optionally included if you were using gcc. This feature proved to be problematic for a number of reasons, most notably that (1) it made the tests non-portable and (2) different releases of gcc handled weak functions in different ways, and therefore it was getting impossible to handle this feature of non-standard C reliably. So it was removed.

If you're using the test runner generator, however, you still have the option (no matter which compiler you're using) because it is now handled by generating a test runner that either includes or does not include calling these functions. 

In your case, you're probably writing your tests manually, and you're stuck including these functions in each of your test files. The good news is that they can be very helpful. The bad news is you will always need them.

**Comment by TooChaos** [comment]
Thank you for very detailed explanation! I am new to Unity so I follow the aforementioned tutorial to try it out, where I encounter this problem.  In light of your explanation, it seems "Getting Started" part there need to be updated.  Thanks again!
