### ISSUE TITLE
Show list of failed tests in the summary

### ISSUE THREAD

**Issue by nbolton** [ThrowTheSwitch/Unity#611]
Within my project, I have many test functions. When one fails, finding out which one is tedious. Filtering is only useful if you know which test will fail (but when you have hundreds of tests, you need to search for the one that failed in the logs).

Idea: Show a list of failed tests in the summary at the end (so you don't have to hunt for failed tests in the log).

**Comment by ivankravets** [comment]
Please close this issue, it is not related to Unity itself. I moved issue to the https://github.com/platformio/platformio-core/issues/4248

**Comment by nbolton** [comment]
Are you sure? Does Unity already have a way of showing the failed tests in the summary?

**Comment by ivankravets** [comment]
Let, @mvandervoord, answer here. What I know is that Unity has a lot of helpers (Ruby scripts). I've not tried them personally. See https://github.com/ThrowTheSwitch/Unity/tree/master/auto

**Comment by mvandervoord** [comment]
Hi guys. Unity itself doesn't print a summary directly. This is intentional as it's meant to be as slim as possible. The example rakefile, Ceedling, and the helper scripts in the auto directory all show ways of providing summaries. Many users are using one of these methods. As a project, we've decided that summaries are part of the larger topic "managing test build suites" which is why we provide Ceedling for those not wishing to roll their own method. 

Make sense?

**Comment by ivankravets** [comment]
Yes, this is exactly how PlatformIO benefits from the Unity project. We have our own test result parser and later provide users output in multiple formats: a rich report in STDOUT, JSON, and JUnit.

**Comment by nbolton** [comment]
@mvandervoord Excellent description. Thank you for taking the time to explain.
@ivankravets I see now, this all makes a lot of sense; it's indeed a Platformio improvement. I'll open it as a new issue (related to summary generation) since it's different to my original one.
