### ISSUE TITLE
Failed test leads to return != 0 and failed GitLab CI pipeline

### ISSUE THREAD

**Issue by umor3** [ThrowTheSwitch/Unity#627]
Greetings,
when running Unity from GitLab Pipeline and an failed test occurs the pipeline fails. This is not the desired behavior. The pipeline is checking the exit code.

Root cause of this is the fact, that Unity returns the number of detected failures before termination. This leads to an error code != 0. And that is marked as a failed terminal command (https://en.wikipedia.org/wiki/Exit_status). Leading to a failed an aborted pipeline. 

A quick and dirty solution for me was to change https://github.com/ThrowTheSwitch/Unity/blob/3852926c00f210905db5feb7a9fa5d5dbf7963ea/src/unity.c#L2097 to
``` c
return 0;
```
That should anyway be the desired result due to the fact that reaching that point in the code without a thrown error should lead to `return 0` .

Or what option am I maybe missing?

Regards
Robert

**Comment by Letme** [comment]
Your logic is totally flawed. Why would you want to return TRUE or SUCCESS when there are failures? If you expect failures, I suggest you look at the thing like https://github.com/melexis/warnings-plugin which will allow you to set the expected number of failures and mask that faulty error code accordingly (only return if there are for example more than 3 failures).

However if there is a failure the CI pipeline should fail and alert you that you should be fixing your unit tests. Point is of whole unit testing is to prevent regression, which means if tests start failing the lights and horns should shout to get it fixed asap.

**Comment by umor3** [comment]
Thanks for the quick reply. Well, I totally get your point but in GitLab you have the possibility to use the JUnit file for that. The test stage failes on the JUnit artefact. At least that how I thought of it.

When Unity rerurns with something else than 0 the pipeline stops. And then you have no chance of converting the result to JUnit because the following command is not executed.

**But** on further thinking: Maybe with an other configuration of the pipline (e. g. with `after_script convert to junit`). Haven't tried. Will report. But have no access till next week.

**Comment by Letme** [comment]
You have one thing wrong: junit is artifact, so it will be DISPLAYED (not fail the build) when you request it and if file is generated. The pipeline will only fail if there is a failure inside the job and like you said in the after script you can convert to junit and have it as artifact displayed in GitLab MR UI. Still job will fail (as it should) alerting you of the problem. Otherwise you can always use the "shell discard return value option" ( `command || true`). But again, I will underline that this is utterly stupid and should not be done in this case, as you lose one of the benefits you got for using Unity in the first place.

**Comment by umor3** [comment]
Okay, got it. I will revert my change and keep it as it is. 

But just wondering: what if Unity itself fails. Some internal error. In that case it should also return with an error code != 0. Even if all test pass succesfully.

**Comment by Letme** [comment]
There internal error you will encounter is Segmentation fault (because in embedded we tend to write to addresses directly, and those are not available/accessible in PC - so you get Segmentation fault for accessing area outside of process memory space) and then OS will kill it. That is non zero (and negative) return value as well. Usually, I would assume it would be a negative value in that case, but I do not remember that Unity has internal error handling - it is fairly lightweight.
