### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by wolf99** [ThrowTheSwitch/Unity#667]
Hi

Seems like quite a few changes since the last release, could there be another?
🙂

**Comment by atticusrussell** [comment]
I agree. I would like the current version to be a release in order to use it correctly with PlatformIO . The last release, [v2.5.2](https://github.com/ThrowTheSwitch/Unity/releases/tag/v2.5.2), does not have support for float and double comparison such as `TEST_ASSERT_GREATER_THAN_DOUBLE`.

The reason I would like this in a new release is that I am running into issues with PlatformIO where the registry only has v2.5.2 from two years ago with slight customization that handle `unity_config.h` for PlatformIO, and when I manually include the last commit from this repo instead of the PlatformIO registry using `lib_deps`, it is missing that customization and has errors.

**Comment by mvandervoord** [comment]
Released v2.6.0
