### ISSUE TITLE
gcc warning: cast from function call of type ‘TEST_error_t’ to non-matching type ‘long long int’

### ISSUE THREAD

**Issue by lazureus** [ThrowTheSwitch/Unity#67]
Hi, 
I've encountered some issue by testing my code, I got some function which definition looks like this : 

```
typedef enum
{
    AAA,
    BBB,
    CCC
} TEST_error_t ;

TEST_error_t TEST_fnc(void)
{
  return AAA ; 
}
```

Then in my test I'm trying to test value which returns the `TEST_fnc()` by invoking following code: 

```
TEST_ASSERT_EQUAL(AAA,TEST_fnc()) ;
```

GCC throws me a warning then that : 

```
cast from function call of type ‘TEST_error_t’ to non-matching type ‘long long int’
```

,when I'm testing return value from the function like this, warning disappears 

```
TEST_error_t ret = TEST_fnc() ;
TEST_ASSERT_EQUAL(AAA,ret) ;
```

I'm working on the 64-bit system, could you please tell am I doing something wrong ?

**Comment by mvandervoord** [comment]
Wow. I forgot to come back to this one. I apologize if anyone was actually waiting on a good response here. 

Giving it some thought, to those who might run into this in the future, I suspect it's that there wasn't a declaration for the function anywhere in the test (or in a header the test included). If it had been added, like so:

extern TEST_error_t TEST_fnc(void);

I bet the error would have gone away. I suspect the problem was that without the function declaration being there, gcc assumed the return value was the biggest int it could... which then didn't fit into the ASSERT.
